In [26]:
import pandas as pd 
import numpy as np

In [27]:
df=pd.read_csv('D:\COURSES\AI\Epsilon Ai\Session 38\Fuel_Veciles\data\processed\datset_feul_cleaned1.csv')
df.head(20)

Unnamed: 0  vehicle_id  year                         make  \
0            4       27550  1984                   AM General   
1            5       28426  1984                   AM General   
2            6       27549  1984                   AM General   
3            7       28425  1984                   AM General   
4            8       27593  1984  American Motors Corporation   
5            9       28455  1984  American Motors Corporation   
6           10       27591  1984  American Motors Corporation   
7           11       27594  1984  American Motors Corporation   
8           12       28454  1984  American Motors Corporation   
9           13       28456  1984  American Motors Corporation   
10          14       27592  1984  American Motors Corporation   
11          15       27595  1984  American Motors Corporation   
12          16       28457  1984  American Motors Corporation   
13          17       27585  1984  American Motors Corporation   
14          18       27588  1984  American Motors Corporation   
15          19       28449  1984  American Motors Corporation   
16          20       28451  1984  American Motors Corporation   
17          21       27586  1984  American Motors Corporation   
18          22       27589  1984  American Motors Corporation   
19          23       28450  1984  American Motors Corporation   

                model                        class  \
0   DJ Po Vehicle 2WD  Special Purpose Vehicle 2WD   
1   DJ Po Vehicle 2WD  Special Purpose Vehicle 2WD   
2    FJ8c Post Office  Special Purpose Vehicle 2WD   
3    FJ8c Post Office  Special Purpose Vehicle 2WD   
4           Eagle 4WD  Special Purpose Vehicle 4WD   
5           Eagle 4WD  Special Purpose Vehicle 4WD   
6           Eagle 4WD  Special Purpose Vehicle 4WD   
7           Eagle 4WD  Special Purpose Vehicle 4WD   
8           Eagle 4WD  Special Purpose Vehicle 4WD   
9           Eagle 4WD  Special Purpose Vehicle 4WD   
10          Eagle 4WD  Special Purpose Vehicle 4WD   
11          Eagle 4WD  Special Purpose Vehicle 4WD   
12          Eagle 4WD  Special Purpose Vehicle 4WD   
13     Eagle SX/4 4WD  Special Purpose Vehicle 4WD   
14     Eagle SX/4 4WD  Special Purpose Vehicle 4WD   
15     Eagle SX/4 4WD  Special Purpose Vehicle 4WD   
16     Eagle SX/4 4WD  Special Purpose Vehicle 4WD   
17     Eagle SX/4 4WD  Special Purpose Vehicle 4WD   
18     Eagle SX/4 4WD  Special Purpose Vehicle 4WD   
19     Eagle SX/4 4WD  Special Purpose Vehicle 4WD   

                         drive       transmission  engine_index  \
0                2-Wheel Drive  Automatic 3-Speed          1830   
1                2-Wheel Drive  Automatic 3-Speed          1880   
2                2-Wheel Drive  Automatic 3-Speed          1831   
3                2-Wheel Drive  Automatic 3-Speed          1881   
4   4-Wheel or All-Wheel Drive  Automatic 3-Speed          1524   
5   4-Wheel or All-Wheel Drive  Automatic 3-Speed          1574   
6   4-Wheel or All-Wheel Drive     Manual 4-Speed          1405   
7   4-Wheel or All-Wheel Drive     Manual 4-Speed          1504   
8   4-Wheel or All-Wheel Drive     Manual 4-Speed          1455   
9   4-Wheel or All-Wheel Drive     Manual 4-Speed          1554   
10  4-Wheel or All-Wheel Drive     Manual 5-Speed          1420   
11  4-Wheel or All-Wheel Drive     Manual 5-Speed          1514   
12  4-Wheel or All-Wheel Drive     Manual 5-Speed          1564   
13  4-Wheel or All-Wheel Drive  Automatic 3-Speed          1430   
14  4-Wheel or All-Wheel Drive  Automatic 3-Speed          1524   
15  4-Wheel or All-Wheel Drive  Automatic 3-Speed          1480   
16  4-Wheel or All-Wheel Drive  Automatic 3-Speed          1574   
17  4-Wheel or All-Wheel Drive     Manual 4-Speed          1405   
18  4-Wheel or All-Wheel Drive     Manual 4-Speed          1504   
19  4-Wheel or All-Wheel Drive     Manual 4-Speed          1455   

    engine_cylinders  ...  hours_to_charge_240v hours_to_charge_ac_240v  \
0                4.0

In [28]:
df.drop(columns=['Unnamed: 0' , 'vehicle_id'], inplace=True)

In [29]:
np.array(df.fuel_economy_score)

array([-1, -1, -1, ...,  5,  7,  5], dtype=int64)

In [30]:
df = df.select_dtypes(include='number')
df

year  engine_index  engine_cylinders  engine_displacement  \
0      1984          1830               4.0                  2.5   
1      1984          1880               4.0                  2.5   
2      1984          1831               6.0                  4.2   
3      1984          1881               6.0                  4.2   
4      1984          1524               6.0                  4.2   
...     ...           ...               ...                  ...   
36789  2017            90               4.0                  2.0   
36790  2017            52               4.0                  2.0   
36791  2017            53               4.0                  2.0   
36792  2017            54               4.0                  2.0   
36793  2017            50               4.0                  2.0   

       city_mpg_ft1  unrounded_city_mpg_ft1  city_mpg_ft2  \
0                18                  0.0000             0   
1                18                  0.0000             0   
2                13                  0.0000             0   
3                13                  0.0000             0   
4                15                  0.0000             0   
...             ...                     ...           ...   
36789            23                 22.6786             0   
36790            20                 20.4122             0   
36791            22                 21.7000             0   
36792            24                 23.7174            54   
36793            22                 22.1000             0   

       unrounded_city_mpg_ft2  city_gasoline_consumption_cd  \
0                      0.0000                        0.0000   
1                      0.0000                        0.0000   
2                      0.0000                        0.0000   
3                      0.0000                        0.0000   
4                      0.0000                        0.0000   
...                       ...                           ...   
36789                  0.0000                        0.0000   
36790                  0.0000                        0.0000   
36791                  0.0000                        0.0000   
36792                 58.5962                        0.0541   
36793                  0.0000                        0.0000   

       city_electricity_consumption  ...  hours_to_charge_240v  \
0                               0.0  ...                   0.0   
1                               0.0  ...                   0.0   
2                               0.0  ...                   0.0   
3                               0.0  ...                   0.0   
4                               0.0  ...                   0.0   
...                             ...  ...                   ...   
36789                           0.0  ...                   0.0   
36790                           0.0  ...                   0.0   
36791                           0.0  ...                   0.0   
36792                          60.0  ...                   3.0   
36793                           0.0  ...                   0.0   

       hours_to_charge_ac_240v  composite_city_mpg  composite_highway_mpg  \
0                          0.0                   0                      0   
1                          0.0                   0                      0   
2                          0.0                   0                      0   
3                          0.0                   0                      0   
4                          0.0                   0                      0   
...                        ...                 ...                    ...   
36789                      0.0                   0                      0   
36790                      0.0                   0                      0   
36791                      0.0                   0                      0   
36792                      0.0                  29                     32   
36793                      0.0                   0          

In [31]:
np.array(df.isnull().sum())

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [32]:
df.columns

Index(['year', 'engine_index', 'engine_cylinders', 'engine_displacement',
       'city_mpg_ft1', 'unrounded_city_mpg_ft1', 'city_mpg_ft2',
       'unrounded_city_mpg_ft2', 'city_gasoline_consumption_cd',
       'city_electricity_consumption', 'city_utility_factor',
       'highway_mpg_ft1', 'unrounded_highway_mpg_ft1', 'highway_mpg_ft2',
       'unrounded_highway_mpg_ft2', 'highway_gasoline_consumption_cd',
       'highway_electricity_consumption', 'highway_utility_factor',
       'unadjusted_city_mpg_ft1', 'unadjusted_highway_mpg_ft1',
       'unadjusted_city_mpg_ft2', 'unadjusted_highway_mpg_ft2',
       'combined_mpg_ft1', 'unrounded_combined_mpg_ft1', 'combined_mpg_ft2',
       'unrounded_combined_mpg_ft2', 'combined_electricity_consumption',
       'combined_gasoline_consumption_cd', 'combined_utility_factor',
       'annual_fuel_cost_ft1', 'annual_fuel_cost_ft2', 'save_or_spend_5_year',
       'annual_consumption_in_barrels_ft1',
       'annual_consumption_in_barrels_ft2', 'tailp

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36794 entries, 0 to 36793
Data columns (total 58 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   year                               36794 non-null  int64  
 1   engine_index                       36794 non-null  int64  
 2   engine_cylinders                   36794 non-null  float64
 3   engine_displacement                36794 non-null  float64
 4   city_mpg_ft1                       36794 non-null  int64  
 5   unrounded_city_mpg_ft1             36794 non-null  float64
 6   city_mpg_ft2                       36794 non-null  int64  
 7   unrounded_city_mpg_ft2             36794 non-null  float64
 8   city_gasoline_consumption_cd       36794 non-null  float64
 9   city_electricity_consumption       36794 non-null  float64
 10  city_utility_factor                36794 non-null  float64
 11  highway_mpg_ft1                    36794 non-null  int

In [34]:
df.corr()

year  engine_index  engine_cylinders  \
year                               1.000000     -0.476106          0.079836   
engine_index                      -0.476106      1.000000         -0.253382   
engine_cylinders                   0.079836     -0.253382          1.000000   
engine_displacement                0.034032     -0.287121          0.901912   
city_mpg_ft1                       0.166459      0.110886         -0.702741   
unrounded_city_mpg_ft1             0.679034     -0.243224         -0.104441   
city_mpg_ft2                       0.149631     -0.063602          0.020196   
unrounded_city_mpg_ft2             0.134931     -0.047615         -0.006190   
city_gasoline_consumption_cd       0.015129     -0.005222          0.008118   
city_electricity_consumption       0.057942     -0.018733         -0.027981   
city_utility_factor                0.057151     -0.018834         -0.036058   
highway_mpg_ft1                    0.262745      0.022213         -0.652132   
unrounded_highway_mpg_ft1          0.692158     -0.248019         -0.081676   
highway_mpg_ft2                    0.173623     -0.075349          0.040552   
unrounded_highway_mpg_ft2          0.159100     -0.056649          0.008691   
highway_gasoline_consumption_cd    0.011132     -0.003925          0.008229   
highway_electricity_consumption    0.058808     -0.019105         -0.029389   
highway_utility_factor             0.057178     -0.018805         -0.035910   
unadjusted_city_mpg_ft1            0.168278      0.105912         -0.685502   
unadjusted_highway_mpg_ft1         0.271887      0.017211         -0.650069   
unadjusted_city_mpg_ft2            0.140923     -0.057964          0.011386   
unadjusted_highway_mpg_ft2         0.172576     -0.072870          0.036167   
combined_mpg_ft1                   0.205937      0.079861         -0.698829   
unrounded_combined_mpg_ft1         0.685939     -0.245738         -0.096076   
combined_mpg_ft2                   0.160697     -0.068954          0.028959   
unrounded_combined_mpg_ft2         0.145545     -0.051562         -0.000250   
combined_electricity_consumption   0.058398     -0.018920         -0.028626   
combined_gasoline_consumption_cd   0.013798     -0.004792          0.008148   
combined_utility_factor            0.057204     -0.018836         -0.036018   
annual_fuel_cost_ft1              -0.101687     -0.104981          0.779721   
annual_fuel_cost_ft2               0.185828     -0.090807          0.156136   
save_or_spend_5_year               0.102510      0.104588         -0.779634   
annual_consumption_in_barrels_ft1 -0.225558     -0.073391          0.737946   
annual_consumption_in_barrels_ft2  0.190688     -0.091030          0.150746   
tailpipe_co2_ft1                   0.598956     -0.200355          0.083914   
tailpipe_co2_in_grams_mile_ft1    -0.226951     -0.076796          0.750473   
tailpipe_co2_ft2                   0.157233     -0.053750          0.074258   
tailpipe_co2_in_grams_mile_ft2     0.185433     -0.090503          0.156843   
fuel_economy_score                 0.591966     -0.198788         -0.112889   
ghg_score                          0.591916     -0.198774         -0.112649   
ghg_score_alt_fuel                 0.158630     -0.053986          0.032101   
x2d_passenger_volume              -0.035256      0.007683         -0.024642   
x2d_luggage_volume                -0.070673      0.015927         -0.040021   
x4d_passenger_volume               0.067926      0.031695         -0.163446   
x4d_luggage_volume                -0.003510      0.055527         -0.157837   
hatchback_passenger_volume        -0.119734      0.198651         -0.276416   
hatchback_luggage_volume          -0.105992      0.197228         -0.250629   
hours_to_charge_120v                    NaN           NaN               NaN   
hours_to_charge_240v               0.056468     -0.018616         -0.033009   
hours_to_charge_ac_240v                 NaN           NaN               NaN   
composite_

In [35]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix , accuracy_score
from sklearn.preprocessing import StandardScaler,PolynomialFeatures
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor
import warnings

warnings.filterwarnings('ignore')

In [36]:
df.shape

(36794, 58)

In [37]:
x=df.drop('fuel_economy_score' , axis=1)
y=df['fuel_economy_score']


In [38]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [39]:
df=pd.get_dummies(df,drop_first=True)
df

year  engine_index  engine_cylinders  engine_displacement  \
0      1984          1830               4.0                  2.5   
1      1984          1880               4.0                  2.5   
2      1984          1831               6.0                  4.2   
3      1984          1881               6.0                  4.2   
4      1984          1524               6.0                  4.2   
...     ...           ...               ...                  ...   
36789  2017            90               4.0                  2.0   
36790  2017            52               4.0                  2.0   
36791  2017            53               4.0                  2.0   
36792  2017            54               4.0                  2.0   
36793  2017            50               4.0                  2.0   

       city_mpg_ft1  unrounded_city_mpg_ft1  city_mpg_ft2  \
0                18                  0.0000             0   
1                18                  0.0000             0   
2                13                  0.0000             0   
3                13                  0.0000             0   
4                15                  0.0000             0   
...             ...                     ...           ...   
36789            23                 22.6786             0   
36790            20                 20.4122             0   
36791            22                 21.7000             0   
36792            24                 23.7174            54   
36793            22                 22.1000             0   

       unrounded_city_mpg_ft2  city_gasoline_consumption_cd  \
0                      0.0000                        0.0000   
1                      0.0000                        0.0000   
2                      0.0000                        0.0000   
3                      0.0000                        0.0000   
4                      0.0000                        0.0000   
...                       ...                           ...   
36789                  0.0000                        0.0000   
36790                  0.0000                        0.0000   
36791                  0.0000                        0.0000   
36792                 58.5962                        0.0541   
36793                  0.0000                        0.0000   

       city_electricity_consumption  ...  hours_to_charge_240v  \
0                               0.0  ...                   0.0   
1                               0.0  ...                   0.0   
2                               0.0  ...                   0.0   
3                               0.0  ...                   0.0   
4                               0.0  ...                   0.0   
...                             ...  ...                   ...   
36789                           0.0  ...                   0.0   
36790                           0.0  ...                   0.0   
36791                           0.0  ...                   0.0   
36792                          60.0  ...                   3.0   
36793                           0.0  ...                   0.0   

       hours_to_charge_ac_240v  composite_city_mpg  composite_highway_mpg  \
0                          0.0                   0                      0   
1                          0.0                   0                      0   
2                          0.0                   0                      0   
3                          0.0                   0                      0   
4                          0.0                   0                      0   
...                        ...                 ...                    ...   
36789                      0.0                   0                      0   
36790                      0.0                   0                      0   
36791                      0.0                   0                      0   
36792                      0.0                  29                     32   
36793                      0.0                   0          

In [40]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [41]:
y_train.value_counts()

fuel_economy_score
-1     24609
 5      1245
 4       921
 6       754
 7       647
 3       412
 8       369
 2       237
 1       103
 9        77
 10       61
Name: count, dtype: int64

In [42]:
df.columns

Index(['year', 'engine_index', 'engine_cylinders', 'engine_displacement',
       'city_mpg_ft1', 'unrounded_city_mpg_ft1', 'city_mpg_ft2',
       'unrounded_city_mpg_ft2', 'city_gasoline_consumption_cd',
       'city_electricity_consumption', 'city_utility_factor',
       'highway_mpg_ft1', 'unrounded_highway_mpg_ft1', 'highway_mpg_ft2',
       'unrounded_highway_mpg_ft2', 'highway_gasoline_consumption_cd',
       'highway_electricity_consumption', 'highway_utility_factor',
       'unadjusted_city_mpg_ft1', 'unadjusted_highway_mpg_ft1',
       'unadjusted_city_mpg_ft2', 'unadjusted_highway_mpg_ft2',
       'combined_mpg_ft1', 'unrounded_combined_mpg_ft1', 'combined_mpg_ft2',
       'unrounded_combined_mpg_ft2', 'combined_electricity_consumption',
       'combined_gasoline_consumption_cd', 'combined_utility_factor',
       'annual_fuel_cost_ft1', 'annual_fuel_cost_ft2', 'save_or_spend_5_year',
       'annual_consumption_in_barrels_ft1',
       'annual_consumption_in_barrels_ft2', 'tailp

In [43]:
models={
    'lr':LogisticRegression(),
    'NBG':GaussianNB(),
    'DTR':DecisionTreeRegressor(),
}

In [44]:
for name,model in models.items():
    print(name)
    model.fit(x_train,y_train)
    y_pred=model.predict(x_train)
    print('train_conf',confusion_matrix(y_train,y_pred))
    print('test_conf',confusion_matrix(y_test,model.predict(x_test)))
    print('acc_train',accuracy_score(y_train,y_pred))
    print('acc_test',accuracy_score(y_test,model.predict(x_test)))
    print('-'*50)

lr
train_conf [[24609     0     0     0     0     0     0     0     0     0     0]
 [    0    88    14     0     0     1     0     0     0     0     0]
 [    0    10   171    56     0     0     0     0     0     0     0]
 [    0     0    33   305    74     0     0     0     0     0     0]
 [    0     0     0    39   817    65     0     0     0     0     0]
 [    0     0     0     0    23  1208    14     0     0     0     0]
 [    0     0     0     0     0    28   702    24     0     0     0]
 [    0     0     0     0     0     0    27   606    10     4     0]
 [    0     0     0     0     0     0     0    22   320    18     9]
 [    0     0     0     0     0     0     0     0    30    46     1]
 [    0     0     0     0     0     0     0     0     1     9    51]]
test_conf [[6162    0    0    0    0    0    0    0    0    0    0]
 [   0   25    2    0    0    0    0    0    0    0    0]
 [   0    3   35   19    0    0    0    0    0    0    0]
 [   0    0    9   77   16    0    0    0 

In [45]:
model=SVR()

In [46]:
model.fit(x_train,y_train)

SVR()

In [47]:
model.score(x_train,y_train)

0.9955209930089363

In [48]:
model.score(x_test,y_test)

0.9943626861698375

In [49]:
import joblib

In [50]:
joblib.dump(model,'feul_model.h5')
joblib.dump(scaler,'feulscaler.h5')

['feulscaler.h5']